package com.zhiyou.ssh.vo;
// Generated 2017-9-7 21:38:41 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="question",catalog="ssh")
public class Question implements java.io.Serializable {

	private Integer qid;
	private Answer answer;
	private Type type;
	private User user;
	private String title;
	private Date pubtime;
	private Integer status;
	private Integer points;
	private Integer count;
	private String content;
	private Set<Answer> answers = new HashSet<>(0);

	public Question() {
	}

	public Question(String title, Date pubtime) {
		this.title = title;
		this.pubtime = pubtime;
	}

	public Question(Answer answer, Type type, User user, String title, Date pubtime, Integer status, Integer points,
			Integer count, String content, Set<Answer> answers) {
		this.answer = answer;
		this.type = type;
		this.user = user;
		this.title = title;
		this.pubtime = pubtime;
		this.status = status;
		this.points = points;
		this.count = count;
		this.content = content;
		this.answers = answers;
	}

	@Id
	@GeneratedValue
	@Column(name="qid",unique=true,nullable=false,length=11)
	public Integer getQid() {
		return this.qid;
	}

	public void setQid(Integer qid) {
		this.qid = qid;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="aid")
	public Answer getAnswer() {
		return this.answer;
	}

	public void setAnswer(Answer answer) {
		this.answer = answer;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="tid")
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="userid")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name="title",nullable=false,length=200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name="pubtime")
	public Date getPubtime() {
		return this.pubtime;
	}

	public void setPubtime(Date pubtime) {
		this.pubtime = pubtime;
	}

	@Column(name="status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name="points",length=11)
	public Integer getPoints() {
		return this.points;
	}

	public void setPoints(Integer points) {
		this.points = points;
	}

	@Column(name="count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Column(name="content",length=65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@OneToMany(cascade=CascadeType.ALL,fetch=FetchType.LAZY,mappedBy="question")
	public Set<Answer> getAnswers() {
		return this.answers;
	}

	public void setAnswers(Set<Answer> answers) {
		this.answers = answers;
	}

}
